version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    networks:
      - app-network
  
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    depends_on:
      api:
        condition: service_healthy
    volumes:
    - ./client:/app
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
  
  client-admin:
    build:
      context: ./client-admin
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - app-network
      
networks:
  app-network:
    driver: bridge
