version: '3.8'

services:
  api:
    build:
      context: ./server
      dockerfile: ./Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    environment:
      - ENVIRONMENT=development
      - LOG_LEVEL=debug
    env_file:
      - .env
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
